### ISSUE TITLE
Tests fails locally

### ISSUE THREAD

**Issue by apraga** [vsbuffalo/scidataflow#23]
Hi, 

Running `cargo test` on main branch (v0.8.11, commit 14e1ccfa406c671fee474d) fails for some tests

```test tests::test_init ... FAILED
test tests::test_add_already_added_error ... FAILED
test tests::test_add_update_status_modified ... FAILED                   
test tests::test_mv ... FAILED
test tests::test_add_already_added_error ... FAILED
```

Details
```
failures:

---- tests::test_init stdout ----
thread 'tests::test_init' panicked at tests/test_project.rs:37:9:
Project::init() did not create 'data_manifest.yml'

---- tests::test_add_already_added_error stdout ----
thread 'tests::test_add_already_added_error' panicked at tests/common/mod.rs:215:38:
setting up TestFixture failed: Failed to load the project configuration

Caused by:
    missing field `user`

---- tests::test_add_update_status_modified stdout ----
thread 'tests::test_add_update_status_modified' panicked at tests/common/mod.rs:215:38:
setting up TestFixture failed: Failed to load the project configuration

Caused by:
    missing field `user`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_mv stdout ----
thread 'tests::test_mv' panicked at tests/test_project.rs:193:61:
called `Result::unwrap()` on an `Err` value: Path 'data/data.tsv' does not exist.


failures:
    tests::test_add_already_added_error
    tests::test_add_update_status_modified
    tests::test_init
    tests::test_mv

test result: FAILED. 2 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s

error: test failed, to rerun pass `--test test_project`
```

There is a data_manifest.yml and a config file though : 
```
❯ cat ~/.scidataflow_config
user:
  name: Joan B. Scientist
  email: joan@ucberkely.edu
  affiliation: UC Berkeley

scidataflow on  main [?] is 📦 v0.8.11 via 🦀 v1.78.0
❯ cat data_manifest.yml
files: []
remotes: {}
metadata:
  title: test_project
  description: null
```
It's surprising that CI passes but not on my computer. Should there be a `data` folder too ?
I'm using nushell if that may be of interest.

Thanks,
